### PR TITLE
Fix Bazel 0.27 compatibility

### LINKED ISSUE #12: Bazel 0.27 incompatible changes
Bazel 0.27 broke those rules:
```
external/platformio_rules/platformio/platformio.bzl", line 77, in _platformio_library_impl
		ctx.new_file(_HEADER_FILENAME.format(dirname ...))
Use ctx.actions.declare_file instead of ctx.new_file. 
Use --incompatible_new_actions_api=false to temporarily disable this check.
```

```
external/platformio_rules/platformio/platformio.bzl", line 87, in _platformio_library_impl
		len(target.files)
depset is not iterable. You may use `len(<depset>.to_list())` instead. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

### PR DESCRIPTION
**Pull request by Kernald**
Fixes #12 

Note that I didn't check if there was a smarter way to fix those changes, I just applied the most straight-forward fixes.

### CODE REVIEW

**Review by mum4k — COMMENTED** [review]
Thank you.

Do we also want to advance the bazel pin up to 0.27?

https://github.com/mum4k/platformio_rules/blob/master/.travis.yml

I can't tell if the build is still working post this PR as the build is currently broken :( If we're not going to advance the bazel pin, can you confirm if this still works / builds?

**Comment by Kernald** [comment]
That's done. I only updated it to 0.27.2 as I know that it works with this version, I don't know about 0.28 since I got the upgrade to PlatformIO 4 at the same time, so my local tree is broken too at the moment.

**Review by mum4k — CHANGES_REQUESTED** [review]
I think we will also need to upload the new SHA sum for bazel here:

https://github.com/mum4k/platformio_rules/tree/master/bazel

**Comment by Kernald** [comment]
Sorry for the delay, I've been travelling the past couple weeks, I'll try to fix that later today.

**Comment by mum4k** [comment]
> Sorry for the delay, I've been travelling the past couple weeks, I'll try to fix that later today.

No worries, please take your time.

**Comment by Kernald** [comment]
Checksum updated!

**Review by mum4k — CHANGES_REQUESTED** [review]
Thank you for the update. Looks like we have a build failure:

https://travis-ci.org/mum4k/platformio_rules/builds/568104904

It might be introduced by this PR, since it currently passes at head:

https://travis-ci.org/mum4k/platformio_rules

Would you mind looking into it?

**Comment by Kernald** [comment]
Sorry, I missed that one! It should be fixed now :-)

**Review by mum4k — APPROVED** [review]
Thank you very much for the contribution.

**Pull request merged**
