### PR TITLE
Use depset in place of set.

### PR DESCRIPTION
**Pull request by ChrisCummins**
Fixes error `name 'set' is not defined` when trying to use these rules by replacing the two uses of `set` with [depset](https://docs.bazel.build/versions/master/skylark/depsets.html).

### CODE REVIEW

**Comment by ChrisCummins** [comment]
I signed it!

**Comment by mum4k** [comment]
Thank you very much for the contribution.

Looks like the tests are failing, maybe because Travis is configured to use a very old version of Bazel (0.5.2)?
https://github.com/mum4k/platformio_rules/blob/master/.travis.yml

The latest seems to be 0.21.0:
https://github.com/bazelbuild/bazel/releases

Do you feel like trying to update .travis.yml and rerunning the checks? Or would you prefer if I do that separately and then come back to this?

**Comment by ChrisCummins** [comment]
Hi @mum4k , thanks for the quick response. I've bumped the bazel version to the latest release, but as you see from the Travis CI history, this unearthed a handful of new issues which I've tried to address. The biggest upset is caused by the deprecation (and error) of `git_repository`, `http_repository`, and `REPOSITORY_NAME`. I've made the required fix to this project's `WORKSPACE` file, but Skydoc and the indirect dependencies haven't all been updated.

As a workaround I've added `--incompatible_package_name_is_a_function=false --incompatible_remove_native_http_archive=false --incompatible_remove_native_git_repository=false` args to the Travis CI bazel invocations, but you may want to take a look and see if that's what you're after.

Cheers,
Chris

**Comment by mum4k** [comment]
Thanks again for pushing through and figuring this out. Your solution looks good, I have filed an issue with myself to eventually remove these flags.

Cheers.

**Review by mum4k — APPROVED** [review]

**Pull request merged**
